name: Simple-Jekyll-Search
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: Unit tests
        run: npm test

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: start server for e2e tests
        run: |
          cd example
          bundle install
          bundle exec jekyll serve --detach

      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:4000"
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        if: contains(github.ref, 'refs/tags/')
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm publish
